version: '2'
services:
  postgres:
    container_name: postgres
    image: pyramation/postgres-plv8
    # image: postgres:10.3
    # build: .
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./db:/sqlext
