-- NOTE: this is generated by skitch, extensions are not actually bundled in final output, just used for testing
-- Deploy extensions/app-extensions to pg
BEGIN;

CREATE EXTENSION IF NOT EXISTS "plpgsql" CASCADE;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" CASCADE;
CREATE EXTENSION IF NOT EXISTS "db-roles" CASCADE;

COMMIT;