-- NOTE: this is generated by skitch, extensions are not actually bundled in final output, just used for testing
-- Verify extensions/app-extensions on pg
BEGIN;

SELECT verify_extension('db-roles');
SELECT verify_extension('uuid-ossp');
SELECT verify_extension('plpgsql');

ROLLBACK;